### ISSUE TITLE
Case insensitive support.

### ISSUE THREAD

**Issue by dahjelle** [IconCMO/pouch-datalog#3]
I don't know how Datomic handles this, but perhaps [this article on IndexedDB](https://hacks.mozilla.org/2014/06/breaking-the-borders-of-indexeddb/?utm_source=html5weekly&utm_medium=email) might have some hints on other ways of accomplishing case-insensitive search.

One could also perhaps just `.toLowerCase()` everything going into the index and coming in as searches, which might be easier and perhaps more efficient in this case.

**Comment by dahjelle** [comment]
Latest commit has case-insensitive support. Perhaps might want to consider making it optional in the future, but closing this for now.

**Comment by jmatsushita** [comment]
I just bumped into this because I didn't use a case insensitive view and it didn't find my docs. I think that given that Couch is case sensitive, pouch-datalog shouldn't be case-insensitive by default!

**Comment by dahjelle** [comment]
Here's the commit that made the case-insensitive: https://github.com/IconCMO/pouch-datalog/commit/ee4826ed0fce93eeca6879c02ec33806b8a2ce34

We'd definitely accept a PR making that optional!
